# --- Global Settings ---
sonar.projectKey=styleaura
sonar.projectName=StyleAura

# --- Authentication ---
# (Usually passed securely via CI/CD pipeline secrets, but defined here if needed)
# sonar.token=your_sonar_token


# --- Source Code Directories ---
# Pointing SonarQube to your specific folder structure
sonar.sources=Backend/StyleAura/src/main/java, Frontend/src
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.mvn/**,**/build/**

# --- Point to compiled Java binaries ---
sonar.java.binaries=Backend/StyleAura/target/classes
