spring.application.name=StyleAura

server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/styleaura_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:StyleAuraSecretKeyForJwtAuthentication2026StyleAura123456}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.org.springframework.security=TRACE
logging.level.com.styleaura=DEBUG
